[keymap]
preset = "default"

[keymap.overrides]

[snippets]
custom_paths = []
include_default_snippets = true

[display]
dataframes = "rich"
default_width = "medium"
default_table_page_size = 10
code_editor_font_size = 14
cell_output = "above"
theme = "light"

[server]
browser = "default"
follow_symlink = false

[completion]
copilot = false
activate_on_typing = true

[language_servers.pylsp]
enable_pyflakes = false
enable_pydocstyle = false
enable_mypy = true
enable_pylint = false
enabled = true
enable_flake8 = false
enable_ruff = true

[ai]
rules = ""

[formatting]
line_length = 79

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[experimental]

[runtime]
default_sql_output = "auto"
auto_instantiate = true
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_reload = "lazy"
output_max_bytes = 30000000
reactive_tests = true
std_stream_max_bytes = 1000000

[package_management]
manager = "uv"
