[package_management]
manager = "uv"

[formatting]
line_length = 79

[display]
code_editor_font_size = 14
default_width = "medium"
default_table_page_size = 10
cell_output = "above"
dataframes = "rich"
theme = "light"

[runtime]
watcher_on_save = "lazy"
reactive_tests = true
on_cell_change = "lazy"
default_sql_output = "auto"
output_max_bytes = 12000000
auto_reload = "off"
std_stream_max_bytes = 1000000
auto_instantiate = false

[keymap]
preset = "default"

[keymap.overrides]

[snippets]
include_default_snippets = true
custom_paths = []

[experimental]

[language_servers.pylsp]
enable_pylint = false
enabled = true
enable_mypy = true
enable_pydocstyle = false
enable_ruff = true
enable_flake8 = false
enable_pyflakes = false

[server]
follow_symlink = false
browser = "default"

[ai]
rules = ""

[completion]
copilot = false
activate_on_typing = true

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"
